FROM docker.io/debian:bookworm-slim

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    wrk \
    ca-certificates \
    curl \
    iputils-ping \
  && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["wrk"]
